<?xml version="1.0" encoding="UTF-8"?>
<leo_file>
<leo_header file_format="2" tnodes="0" max_tnode_index="0" clone_windows="0"/>
<globals body_outline_ratio="0.5">
	<global_window_position top="122" left="303" height="600" width="800"/>
	<global_log_window_position top="0" left="0" height="0" width="0"/>
</globals>
<preferences/>
<find_panel_settings/>
<vnodes>
<v t="ekr.20041220170140" a="E"><vh>An outline to test Resolve CVS Conflicts command</vh>
<v t="ekr.20041220170413" a="E"><vh>@thin cvsConflict.py</vh></v>
</v>
</vnodes>
<tnodes>
<t tx="ekr.20041220170140"></t>
</tnodes>
</leo_file>
