#!/bin/sh

############################################
# This is a small install script to install
# leo on GNU/Linux. 
# Leo is Open Software and is distributed under the terms 
# of the Python License.  Please see:
# docs/LICENSE.TXT for details.
#
# This install script created by Frank Merenda 
# (fmerenda@yahoo.com)
#
# version 1.0 - 06/30/2003
# - initial creation
# version 1.1 - 08/28/2003 EKR
# - Change step 5 below.
#
############################################


################################
# Variables for usage in this script.
################################
LEO_RUN_SCRIPT_SOURCE='./scripts/install/leo-script.txt'
LEO_RUN_SCRIPT_OUTPUT='/usr/bin/leo'
LEO_LIB_DIR='/usr/lib/leo'

################################
# Step 1
# Verify the current user is root
################################
CURRENT_USER=$(whoami)

if [ "$CURRENT_USER" = "root" ] ; then
    echo Verified user is root
else
    echo You must be root to run this program
    exit 0;
fi    
   
################################
# Step 2
# Make the directory structure
################################
echo Making directory structure $LEO_LIB_DIR

RESULTS=`mkdir -p $LEO_LIB_DIR 2>&1`
if [ $? -ne 0 ]; then
    echo Failure making directory $LEO_LIB_DIR!
    exit 0;
fi
   
################################
# Step 3
# Copy the files
################################
echo Copying files.....

RESULTS=`cp -rp * $LEO_LIB_DIR/ 2>&1`
if [ $? -ne 0 ]; then
    echo Failure copying files to $LEO_LIB_DIR
    exit 0;
fi

###############################
# Step 4
# Clean up the duplicate files so it's not
# confusing to the user. These files
# Are copied directly to the main 
# directory. Assume you have permissions
# since you checked above.
###############################
rm -rf $LEO_LIB_DIR/src
rm -rf $LEO_LIB_DIR/config
   
###############################
# Step 5
# Don't make a liar out of me in step 4.
# Copy the files. that you just deleted....   
###############################

# 8/22/03: copy the entire directory
#cp -rp src/* $LEO_LIB_DIR/
#cp -rp config/* $LEO_LIB_DIR/

cp -rp src $LEO_LIB_DIR/.
cp -rp config $LEO_LIB_DIR/.

###############################
# Step 6
# Add in symbolic links to point to 
# leoConfig and LeoDocs.   
###############################
mkdir -p /usr/lib/config 
chmod 777 /usr/lib/config
ln -sf /$LEO_LIB_DIR/leoConfig.leo /usr/lib/config/leoConfig.leo
chmod 666 /$LEO_LIB_DIR/leoConfig.leo  

ln -sf /$LEO_LIB_DIR/leoConfig.txt /usr/lib/config/leoConfig.txt
chmod 666 /$LEO_LIB_DIR/leoConfig.txt  

mkdir -p /usr/lib/doc
ln -sf $LEO_LIB_DIR/doc/LeoDocs.leo /usr/lib/doc/LeoDocs.leo
chmod 666 $LEO_LIB_DIR/doc/LeoDocs.leo 
   
################################
# Step 7
# Create the startup script
################################
echo Creating startup script located at: $LEO_RUN_SCRIPT_OUTPUT

# RESULTS=`cp $LEO_RUN_SCRIPT_SOURCE $LEO_RUN_SCRIPT_OUTPUT`
echo "python /usr/lib/leo/src/leo.py \"> $LEO_RUN_SCRIPT_OUTPUT

RESULTS=`chmod 755 $LEO_RUN_SCRIPT_OUTPUT`   
   
echo "***** Leo installed successfully - type 'leo filename.leo' to use it."   
exit 0;
   

